language: node_js
sudo: true
node_js:
  - '10.16'
before_install:
  - yarn audit
install:
  - yarn
script:
  - yarn run build
  - docker build -t microscope .
  - docker run --name microscope -d -p 8080:80 microscope
  - curl 127.0.0.1:8080
